[Service]
LoadCredentialEncrypted=test_db_password:/opt/services/vault/credstore/test_db_password.cred
Environment=DB_PASSWORD_FILE=/run/credentials/%N/test_db_password
LoadCredentialEncrypted=test_internal_service_jwt_secret:/opt/services/vault/credstore/test_internal_service_jwt_secret.cred
Environment=INTERNAL_SERVICE_JWT_SECRET_FILE=/run/credentials/%N/test_internal_service_jwt_secret
LoadCredentialEncrypted=test_enc_key:/opt/services/vault/credstore/test_enc_key.cred
Environment=ENC_KEY_FILE=/run/credentials/%N/test_enc_key
NoNewPrivileges=yes
ProtectSystem=strict
ProtectHome=read-only
PrivateTmp=yes
ProtectKernelTunables=yes
ProtectKernelModules=yes
ProtectControlGroups=yes
LockPersonality=yes
MemoryDenyWriteExecute=yes
